import type { ITheme } from "@xterm/xterm";

export interface AetherTheme {
  id: string;
  name: string;
  xterm: ITheme;
}

export const THEMES: AetherTheme[] = [
  {
    id: "midnight",
    name: "Midnight",
    xterm: {
      background: "#0d1016",
      foreground: "#eaeef6",
      cursor: "#7c9aff",
      cursorAccent: "#0d1016",
      selectionBackground: "#7c9aff59",
      black: "#11151c",
      red: "#f0646e",
      green: "#50c882",
      yellow: "#f0b450",
      blue: "#7c9aff",
      magenta: "#c490ff",
      cyan: "#5fd8e3",
      white: "#c5cad6",
      brightBlack: "#3a4258",
      brightRed: "#ff8088",
      brightGreen: "#7ce0a3",
      brightYellow: "#ffd084",
      brightBlue: "#a3b8ff",
      brightMagenta: "#dab1ff",
      brightCyan: "#85e8f0",
      brightWhite: "#eaeef6",
    },
  },
  {
    id: "monokai-pro",
    name: "Monokai Pro",
    xterm: {
      background: "#2d2a2e",
      foreground: "#fcfcfa",
      cursor: "#ffd866",
      selectionBackground: "#ffd86640",
      black: "#403e41",
      red: "#ff6188",
      green: "#a9dc76",
      yellow: "#ffd866",
      blue: "#fc9867",
      magenta: "#ab9df2",
      cyan: "#78dce8",
      white: "#fcfcfa",
      brightBlack: "#727072",
      brightRed: "#ff6188",
      brightGreen: "#a9dc76",
      brightYellow: "#ffd866",
      brightBlue: "#fc9867",
      brightMagenta: "#ab9df2",
      brightCyan: "#78dce8",
      brightWhite: "#fcfcfa",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    xterm: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    xterm: {
      background: "#1a1b26",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      selectionBackground: "#33467c",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },
];

export const DEFAULT_THEME = THEMES[0]!;
